spring:
  data:
      mongodb:
        uri:mongodb+srv://gerhardgaube:test12345@testgerhard.0rechap.mongodb.net/

    #mongodb+srv://mongodb:mongodb://localhost:27017
      database: swd232

server:
  port: 5000
  service-name: lab2-rest-mongodbatlas




